name:                vinyl-loeb
version:             0.0.1.0
git:                 https://gitlab.com/homotopic-tech/vinyl-loab
license:             MIT
author:              "Daniel Firth"
maintainer:          "dan.firth@homotopic.tech"
copyright:           "2020 Daniel Firth"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Loeb's theorem for extensible records.
category:            Vinyl

dependencies:
- base >= 4.7 && < 5
- vinyl

library:
  source-dirs: src

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
